# Generated by Django 4.0.1 on 2022-05-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='companyName',
            new_name='company',
        ),
    ]
