# Generated by Django 4.0.1 on 2022-05-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_companyname_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='programmingLanguage',
            new_name='proglanguage',
        ),
    ]
