# Generated by Django 4.0.1 on 2022-05-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_programminglanguage_job_proglanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='publishedDate',
            new_name='published',
        ),
    ]
