# Generated by Django 4.0.1 on 2022-06-03 09:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='introduceYourself',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
