# Generated by Django 4.0.1 on 2022-06-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_user_job_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='author',
            new_name='user',
        ),
    ]
