# Generated by Django 4.0.1 on 2022-06-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_job_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='author',
        ),
    ]
