# Generated by Django 4.0.1 on 2022-06-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_rename_proglanguage_job_programminglanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='programminglanguage',
            new_name='proglanguage',
        ),
    ]
