# Generated by Django 4.0.1 on 2022-06-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='proglanguage',
            new_name='language',
        ),
    ]
