# Generated by Django 4.0.1 on 2022-06-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_rename_proglanguage_job_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='language',
            new_name='proglanguage',
        ),
    ]
