# Generated by Django 4.0.1 on 2022-06-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_rename_language_job_proglanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
    ]
